plugin: amazon.aws.aws_ec2
use_contrib_script_compatible_ec2_tag_keys: false

regions:
  - eu-central-1

filters:
  tag:Project: task-manager
  instance-state-name: running

compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'~/.ssh/id_ed25519'"

groups:
  app_servers: "'task-manager' in tags.get('Project', '')"cur